### ISSUE TITLE
端口占用，语言错误

### ISSUE THREAD

**Issue by Adogs1** [kmcsr/smart_servertime_mcdr#3]
在添加本插件及其3个依赖以后，我原本安装在fabric上的Geyser出现如下报错
[08:01:36] [Server thread/WARN]: **** FAILED TO BIND TO PORT!
[08:01:36] [Server thread/WARN]: The exception was: java.net.BindException: Address already in use: bind
[08:01:36] [Server thread/WARN]: Perhaps a server is already running on that port?
[08:01:36] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:680) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[08:01:36] [Server thread/ERROR]: This crash report has been saved to: E:\GVS_Minecraft server start\server\.\crash-reports\crash-2023-12-03_08.01.36-server.txt
[08:01:36] [Server thread/INFO]: Geyser关闭中
[08:01:36] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ScheduledExecutorService.shutdown()" because "this.scheduledThread" is null
	at org.geysermc.geyser.GeyserImpl.shutdown(GeyserImpl.java:591) ~[geyser-fabric-2.2.0-SNAPSHOT+build.357.jar:?]
	at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onDisable(GeyserFabricMod.java:206) ~[geyser-fabric-2.2.0-SNAPSHOT+build.357.jar:?]
	at org.geysermc.geyser.platform.fabric.GeyserFabricMod.lambda$onEnable$1(GeyserFabricMod.java:126) ~[geyser-fabric-2.2.0-SNAPSHOT+build.357.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:63) ~[fabric-lifecycle-events-v1-2.2.2+b1792f7da0-6534456d0dd033b3.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cgc000$fabric-lifecycle-events-v1$beforeShutdownServer(MinecraftServer.java:7856) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:542) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:699) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

还有，启动时mcdr也有红字报错：
[MCDR] [08:14:37] [TaskExecutor/ERROR]: Error translate text "login_proxy.messages.warn.port_might_same" to language zh_cn
[MCDR] [08:14:37] [TaskExecutor/WARNING] [loginproxy]: login_proxy.messages.warn.port_might_same
[MCDR] [08:14:37] [TaskExecutor/ERROR]: Error translate text "login_proxy.messages.warn.port_might_same" to language zh_cn

**Comment by zyxkad** [comment]
请调整配置文件，`loginproxy`的端口不能与`minecraft`的端口重复

**Comment by wucy777** [comment]
> 请调整配置文件，的端口不能与的端口重复`loginproxy``minecraft`

但是它默认就是25565啊（捂脸

**Comment by zyxkad** [comment]
错误信息已在 <https://github.com/kmcsr/login_proxy_mcdr/releases/tag/v0.6.3> 中修复

**Comment by wucy777** [comment]
> 错误信息已在 https://githubfast.com/kmcsr/login_proxy_mcdr/releases/tag/v0.6.3 中修复

我修改成25566，以上问题得到解决

**Comment by wucy777** [comment]
> 错误信息已在 https://githubfast.com/kmcsr/login_proxy_mcdr/releases/tag/v0.6.3 中修复

不应该在插件中设置loginproxy的非25565端口吗，提醒修改minecraft的默认端口25565将导致其他代理原版服务器的某些连接出错？

**Comment by zyxkad** [comment]
> > 错误信息已在 https://githubfast.com/kmcsr/login_proxy_mcdr/releases/tag/v0.6.3 中修复
> 
> 不应该在插件中设置loginproxy的非25565端口吗，提醒修改minecraft的默认端口25565将导致其他代理原版服务器的某些连接出错？

不，loginproxy的作用就是隐藏minecraft服务器，您应该公开loginproxy的端口而不是minecraft的，故此默认端口与minecraft相同

**Comment by wucy777** [comment]
> > > 错误信息已在 https://githubfast.com/kmcsr/login_proxy_mcdr/releases/tag/v0.6.3 中修复
> > 
> > 
> > 不应该在插件中设置loginproxy的非25565端口吗，提醒修改minecraft的默认端口25565将导致其他代理原版服务器的某些连接出错？
> 
> 不，loginproxy的作用就是隐藏minecraft服务器，您应该公开loginproxy的端口而不是minecraft的，故此默认端口与minecraft相同

所以minecraft的端口设置为其他，丢在一旁放着不用就行了？或许它应该在自述文件中有所说明

**Comment by zyxkad** [comment]
> 所以minecraft的端口设置为其他，丢在一旁放着不用就行了？或许它应该在自述文件中有所说明

README里面已经写了💦

**Comment by wucy777** [comment]
> > 所以minecraft的端口设置为其他，丢在一旁放着不用就行了？或许它应该在自述文件中有所说明
> 
> README里面已经写了 💦

最后一个问题💦minecraft的query.port需要一起改吗，还是说在启用反向代理以后不需要管它（默认也是25565

**Comment by zyxkad** [comment]
> 最后一个问题💦minecraft的query.port需要一起改吗，还是说在启用反向代理以后不需要管它（默认也是25565

我没记错query.port用的是UDP协议，而loginproxy仅代理TCP，所以不会冲突

**Comment by wucy777** [comment]
> > 最后一个问题💦minecraft的query.port需要一起改吗，还是说在启用反向代理以后不需要管它（默认也是25565
> 
> 我没记错query.port用的是UDP协议，而loginproxy仅代理TCP，所以不会冲突

谢谢！！！

**Comment by Adogs1** [comment]
> > 最后一个问题💦minecraft的query.port需要一起改吗，还是说在启用反向代理以后不需要管它（默认也是25565
> 
> 我没记错query.port用的是UDP协议，而loginproxy仅代理TCP，所以不会冲突

现在玩家无法加入服务器，这是安装这些插件的第一次测试
[
![Uploading QQ截图20231203124325.png…]()
](url)

**Comment by wucy777** [comment]
> > 最后一个问题💦minecraft的query.port需要一起改吗，还是说在启用反向代理以后不需要管它（默认也是25565
> 
> 我没记错query.port用的是UDP协议，而loginproxy仅代理TCP，所以不会冲突

现在玩家无法加入服务器，这是安装这些插件的第一次测试
![QQ截图20231203124325](https://github.com/kmcsr/smart_servertime_mcdr/assets/111733210/885a8b3a-b955-4327-9400-6e133d9a28d6)

**Comment by zyxkad** [comment]
插件仅支持1.8 ~ 1.19

**Comment by wucy777** [comment]
> 插件仅支持1.8 ~ 1.19

不能兼容1.20？

**Comment by zyxkad** [comment]
做插件的时候1.19刚发布，然后就没管了（

**Comment by zyxkad** [comment]
建议去loginproxy的repo下面开个issue
